#!/usr/bin/python


class Message:
    id_message = ""
    platform = ""
    subject = ""
    sender = ""
    to_m = []
    content = ""
    time_to_send = ""
    message_status = ""
    def __init__(self, id_message, platform, subject, sender, to_m, content, time_to_send, message_status):
        self.id_message = id_message
        self.platform = platform
        self.subject = subject
        self.sender = sender
        self.to_m = to_m
        self.content = content
        self.time_to_send = time_to_send
        self.message_status = message_status


a = Message("1", "G", "Papa", "rafaelsuazoh@gmail.com", ["chacha@gmail.com"], "PEROPAPAAAA", "12:20121212", "NS")
print(a.to_m)
